on: [push, pull_request]
jobs:
  ignore-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: repo_branch
        if: 'git branch --show-current' != 'ga-ignore-*'
        run: date