name: Chocolatine

on: 
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DOP-200-LIL-2-1-chocolatine-simon.riembault.git"
  EXECUTABLES: "a.out,pushswa"

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    name: Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: check_repo_cleanliness
        run: |
            for i in $(find . -type f -name "*.o" -o -name "#*#" -o -name "*~" -o -name "*.a" -o -name "*.so" -o -iname "*pain_au_chocolat*" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -type d -name "tmp");
            do echo "::error title=Unwanted file detected,file=${i}::${i}";
            done;
            number=$(find . -type f -name "*.o" -o -name "#*#" -o -name "*~" -o -name "*.a" -o -name "*.so" -o -iname "*pain_au_chocolat*" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -type d -name "tmp" | wc -l)
            if [ ${number} -gt 0 ];
              then exit 1;
            fi;

  check_program_compilation:
    runs-on: ubuntu-latest
    name: Checks if the repository contains the right binary files and that these files are executable
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: make
        run: make
        timeout-minutes: 2
      - name: make clean
        run: make clean
      - name: check_exec
        run: |
          exec_list=${{env.EXECUTABLES}}
          parse_sep=$IFS
          IFS=,
          for binaries in $exec_list;
          do
            if test ! -x $binaries;
              then
                echo "::error title=Build Error,file=${binaries}::${binaries}";
                exit 1;
            fi;
          done;

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    needs:
      - check_repository_cleanliness
      - run_tests
      - check_program_compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}