name: Chocolatine

on: 
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-LIL-2-1-chocolatine-simon.riembault.git"
  EXECUTABLES: "pushswap"

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: date
        run: date
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-LIL-2-1-chocolatine-simon.riembault.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}