name: Chocolatine

on: 
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-LIL-2-1-chocolatine-simon.riembault.git"
  EXECUTABLES: "pushswap"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: dates
        run: date