name: Chocolatine

on: 
  push:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  ignore-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: repo_branch
        run: date