on: push
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: repo_branch
        run: git branch --show-current
      - name: repo_size
        run: du -skh --exclude=".git"